package com.joaomanaia.game2048.core.ui

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF745b00)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffe07f)
val md_theme_light_onPrimaryContainer = Color(0xFF241a00)
val md_theme_light_secondary = Color(0xFF695e3f)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf1e1bb)
val md_theme_light_onSecondaryContainer = Color(0xFF221b04)
val md_theme_light_tertiary = Color(0xFF47664b)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc8ebc9)
val md_theme_light_onTertiaryContainer = Color(0xFF03210c)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbf7)
val md_theme_light_onBackground = Color(0xFF1e1b16)
val md_theme_light_surface = Color(0xFFfffbf7)
val md_theme_light_onSurface = Color(0xFF1e1b16)
val md_theme_light_surfaceVariant = Color(0xFFebe1cf)
val md_theme_light_onSurfaceVariant = Color(0xFF4c4639)
val md_theme_light_outline = Color(0xFF7d7667)
val md_theme_light_inverseOnSurface = Color(0xFFf7f0e7)
val md_theme_light_inverseSurface = Color(0xFF33302a)
val md_theme_light_inversePrimary = Color(0xFFedc22e)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFedc22e)
val md_theme_dark_onPrimary = Color(0xFF3d2f00)
val md_theme_dark_primaryContainer = Color(0xFF574400)
val md_theme_dark_onPrimaryContainer = Color(0xFFffe07f)
val md_theme_dark_secondary = Color(0xFFd4c5a0)
val md_theme_dark_onSecondary = Color(0xFF383016)
val md_theme_dark_secondaryContainer = Color(0xFF50462a)
val md_theme_dark_onSecondaryContainer = Color(0xFFf1e1bb)
val md_theme_dark_tertiary = Color(0xFFaccfae)
val md_theme_dark_onTertiary = Color(0xFF18371f)
val md_theme_dark_tertiaryContainer = Color(0xFF2f4d34)
val md_theme_dark_onTertiaryContainer = Color(0xFFc8ebc9)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1e1b16)
val md_theme_dark_onBackground = Color(0xFFe9e2d9)
val md_theme_dark_surface = Color(0xFF1e1b16)
val md_theme_dark_onSurface = Color(0xFFe9e2d9)
val md_theme_dark_surfaceVariant = Color(0xFF4c4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFcfc6b4)
val md_theme_dark_outline = Color(0xFF989080)
val md_theme_dark_inverseOnSurface = Color(0xFF1e1b16)
val md_theme_dark_inverseSurface = Color(0xFFe9e2d9)
val md_theme_dark_inversePrimary = Color(0xFF745b00)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFFedc22e)
val error = Color(0xFFba1b1b)
